version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 cp s3://ki2147-bucket/.env ./productapi/.env
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 983287632230.dkr.ecr.us-east-2.amazonaws.com
      - docker build -t productapp_api .
      - docker tag productapp_api:latest 983287632230.dkr.ecr.us-east-2.amazonaws.com/productapp_api:1.0
      - docker push 983287632230.dkr.ecr.us-east-2.amazonaws.com/productapp_api:1.0
