version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - yum install -y pkg-config
      - pip install -r requirements.txt  # Install project dependencies

  pre_build:
    commands:
      - aws s3 cp s3://ki2147-bucket/requirements.txt ./requirements.txt  # Download requirements.txt
      - aws s3 cp s3://ki2147-bucket/.env ./productapi/.env  # Download .env file

  build:
    commands:
      - pytest  # Execute the pytest command

artifacts:
  files:
    - '**/*'  # Include all files and directories in the build artifact
