# Generated by Django 4.2.2 on 2023-06-23 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
